name: test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: JamieMagee/notice-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}